spring:
  datasource:
    url: jdbc:postgresql://ep-red-unit-ad718262-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_w0OBoDYizb9J
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari: DEBUG

api:
  security:
    token:
      secret: pjinsights1234567

aws:
  api:
    profile-classifier:
      url: "https://1r4rllo8ff.execute-api.sa-east-1.amazonaws.com/Prod"

